services:
  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/courses-front:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - API_BASE_URL=http://backend:8000
  
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    volumes:
      - ./tg_bot:/app

    env_file:
      - .env
    # environment:
    #   - API_BASE_URL=http://backend:8000  # Для доступа к бэкенду
    depends_on:
      - backend


