services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./courses:/app/courses
    env_file:
      - .env
  bot:
    build:
      context: .
      dockerfile: bot.Dockerfile
    container_name: telegram_bot
    volumes:
      - .:/app
    depends_on:
      - backend
    restart: unless-stopped